openapi: 3.0.0
info:
  title: My Backend For Frontend
  version: 1.0.0
  description: My Backend For Frontend
servers:
  - url: http://localhost:4200/api/backend
    description: Development server
paths:
  /users/{id}:
    get:
      summary: Get user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserByIdResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserByIdBadRequestResponse'
components:
  schemas:
    GetUserByIdResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
    GetUserByIdBadRequestResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
            details:
              type: object
              properties:
                id:
                  type: array
                  items:
                    type: string
